[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "orion-atlas"
authors = [{name = "The ATLAS Collaboration", email = "jbeirer@cern.ch"}]
dynamic = ["version", "description"]
